# This is the network config written by 'subiquity'
network:
  ethernets:
    ens3:
      dhcp4: true
    ens8:
      dhcp4: false
      addresses:
              - 10.10.5.5/24
      routes:
              - to: 10.10.5.0/24
                scope: link
    ens9:
      dhcp4: false
      addresses:
              - 10.10.6.5/24
      routes:
              - to: 10.10.6.0/24
                scope: link
    ens16:
      dhcp4: false
      addresses:
              - 10.10.4.5/24
      routes:
              - to: 10.10.4.0/24
                scope: link
    ens17:
      dhcp4: false
      addresses:
              - 10.10.3.5/24
      routes:
              - to: 10.10.3.0/24
                scope: link
  version: 2
